/**
 * QUIZVERSE — certificate tests (app/certificate.js)
 * Run:  node --test tests
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';

import { certificateModel, certificateSVG, certificateHTML, certificateFileName } from '../app/certificate.js';

const winnerResult = {
  student_name: 'Aarav', topic: 'Solar System', subject: 'Science', class_level: 5,
  score: 4200, max_score: 6300, accuracy: 86.7, correct: 13, questions_answered: 15,
  stage_reached: 5, stages_cleared: 5, status: 'WINNER', time_taken_seconds: 272,
  lifelines_used: ['clue'],
  per_stage: [{ stage: 1, correct: 3, total: 3, passed: true }],
  per_question: [
    { question_id: 'a', is_correct: false, concept_tag: 'planet identity' },
    { question_id: 'b', is_correct: true, concept_tag: 'orbits' },
  ],
};

test('model distinguishes winner from participation, never humiliating', () => {
  const winner = certificateModel(winnerResult, { locale: 'en', date: new Date(2025, 8, 14) });
  assert.equal(winner.is_winner, true);
  assert.equal(winner.title, 'CERTIFICATE OF ACHIEVEMENT');
  assert.equal(winner.time_text, '04:32');
  assert.equal(winner.date_text, '14 September 2025');

  const effort = certificateModel({ ...winnerResult, status: 'NOT_CLEARED', score: 1200 }, { locale: 'en', date: new Date(2025, 8, 14) });
  assert.equal(effort.is_winner, false);
  assert.equal(effort.title, 'CERTIFICATE OF PARTICIPATION');
  assert.match(effort.subtitle, /keep going/i);
  assert.ok(!/fail|lose|stupid/i.test(effort.title + effort.subtitle));
});

test('Hindi locale formats the date in Devanagari and localises the title', () => {
  const model = certificateModel(winnerResult, { locale: 'hi', date: new Date(2025, 8, 14) });
  assert.equal(model.date_text, '14 सितंबर 2025');
  assert.match(model.title, /[\u0900-\u097F]/);
  assert.equal(model.time_text, '04:32');
});

test('verification code is deterministic and content-derived', () => {
  const a = certificateModel(winnerResult).verification_code;
  const b = certificateModel(winnerResult).verification_code;
  const c = certificateModel({ ...winnerResult, score: 1 }).verification_code;
  assert.equal(a, b, 'same result → same code');
  assert.notEqual(a, c, 'different result → different code');
  assert.match(a, /^[0-9A-Z]{8}$/);
});

test('svg is standalone, deterministic and carries the required data attributes', () => {
  const model = certificateModel(winnerResult, { school_name: 'Sarita Vidya Mandir' });
  const svg = certificateSVG(model);
  assert.ok(svg.startsWith('<svg'));
  assert.ok(svg.endsWith('</svg>'));
  assert.ok(svg.includes('data-student="Aarav"'));
  assert.ok(svg.includes('data-topic="Solar System"'));
  assert.ok(svg.includes('data-score="4200"'));
  assert.ok(svg.includes('QUIZVERSE'));
  assert.ok(svg.includes('LEARN · THINK · WIN'));
  assert.ok(svg.includes('Sarita Vidya Mandir'));
  assert.ok(svg.includes('04:32'));
  assert.equal(svg, certificateSVG(model), 'deterministic for the same input');
  assert.ok(!/(?:src|href)\s*=\s*["']https?:/.test(svg), 'no external assets');
  assert.ok(!/<img/i.test(svg));
});

test('hostile and broken inputs never leak or crash', () => {
  const hostile = certificateModel({ student_name: '<script>alert(1)</script>', topic: 'x', score: -5, accuracy: 999, status: 'WINNER' });
  const svg = certificateSVG(hostile);
  const html = certificateHTML(hostile);
  assert.ok(!svg.includes('<script>'), 'name is escaped');
  assert.ok(!html.includes('<script>'));
  assert.ok(!/undefined|NaN|null/i.test(svg), 'no NaN/undefined/null in the svg');
  assert.ok(!/undefined|NaN|null/i.test(html), 'no NaN/undefined/null in the html');

  const broken = certificateSVG(certificateModel({}));
  assert.ok(!/undefined|NaN|null/i.test(broken), 'empty result renders a safe default');

  const long = certificateSVG(certificateModel({ student_name: 'A'.repeat(200) }));
  assert.ok(long.includes('…'), 'absurdly long names are truncated in the visual');
});

test('html includes print CSS, the svg and a stage table', () => {
  const html = certificateHTML(certificateModel(winnerResult));
  assert.ok(html.includes('<style>'));
  assert.ok(html.includes('@media print'));
  assert.ok(html.includes('@page'));
  assert.ok(html.includes('<svg'));
  assert.ok(html.includes('Stage'));
  assert.ok(html.includes('Generated by QUIZVERSE'));
});

test('file name is safe, deterministic and portable', () => {
  const name = certificateFileName(certificateModel({ student_name: 'Aarav', topic: 'Solar System' }, { date: new Date(2025, 8, 14) }));
  assert.equal(name, 'quizverse-certificate-aarav-solar-system-14-september-2025');
  assert.ok(!/[\\/:*?"<>|]/.test(name));
  assert.ok(name.length <= 80);

  const devanagari = certificateFileName(certificateModel({ student_name: 'आरव', topic: 'सौरमंडल' }, { date: new Date(2025, 8, 14) }));
  assert.ok(!/[\u0900-\u097F]/.test(devanagari), 'non-ASCII is transliterated out of the filename');
  assert.ok(devanagari.startsWith('quizverse-certificate-'));
  assert.ok(devanagari.length > 0);
});

test('concept strengths and weaknesses are computed from per_question', () => {
  const model = certificateModel(winnerResult);
  assert.deepEqual(model.strong, ['orbits']);
  assert.deepEqual(model.weak, ['planet identity']);
});
